CREATE DATABASE GAME_OF_LIFE
CREATE TABLE [START](
	ID INT PRIMARY KEY IDENTITY(1,1),
	[START_DATE]  DATETIME DEFAULT GETDATE(),
	WIDTH INT NOT NULL,
	HEIGHT INT NOT NULL,
);
GO
CREATE TABLE MATRIX(
	ID_STATE INT PRIMARY KEY IDENTITY(1,1),
	STEP INT NOT NULL,
	BOARD_ID INT NOT NULL,
	X INT NOT NULL,
	Y INT NOT NULL,
	FOREIGN KEY (BOARD_ID) REFERENCES [START](ID)
);
go